name: Release and Publish

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.3"

      - name: Install dependencies
        run: npm ci

      - name: Bump version and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          npm version patch
          git add package.json package-lock.json
          git commit -m "ci: bump version to $(node -p -e "require('./package.json').version")" || echo "No changes to commit"
          git push
          git tag v$(node -p -e "require('./package.json').version")
          git push origin --tags

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
